# frozen_string_literal: true

require "erb"
require "json"
require_relative "ruby_grammar"

module Arpaka
  class Generator
    def generate(ruby_source:, class_name:)
      unless /\A[A-Z][a-zA-Z0-9_]*\z/.match?(class_name)
        raise Error, "class_name must be a single Ruby constant name"
      end
      unless ::Ruby::Box.enabled?
        raise Error, "Ruby Box is required for generation. Start Ruby with RUBY_BOX=1."
      end
      artifacts = RubyGrammar.artifacts(ruby_source: ruby_source)
      parser = Lrama::Ruby.generate(artifacts.fetch("parse.y"),
        filename: File.join(ruby_source, "parse.y"), class_name: "Parser", allow_error_rules: true)
      parser = parser.delete_prefix("# frozen_string_literal: true\n")
      rules = JSON.parse(artifacts.fetch("rules.json"))
      runtime = %w[frontend ast builder lexer].map do |name|
        template = File.read(File.join(__dir__, "runtime", "#{name}.rb.erb"))
        name == "builder" ? ERB.new(template).result_with_hash(rules: rules) : template
      end.join("\n")
      notices = [File.read(File.expand_path("../../LICENSE.txt", __dir__))]
      %w[COPYING BSDL].each { |name| notices << File.read(File.join(ruby_source, name)) }
      source = "# frozen_string_literal: true\n" \
        "# Generated by Arpaka #{Lrama::Ruby::VERSION}. Do not edit.\n" \
        "# Ruby source profile: #{RubyGrammar::REVISION}\n" \
        "# parse.y SHA256: #{Digest::SHA256.file(File.join(ruby_source, 'parse.y')).hexdigest}\n" \
        "#{notices.join("\n").lines.map { |line| "# #{line}" }.join}\n" \
        "class #{class_name}\n#{parser}\n#{runtime}\nend\n"
      # Compile in an isolated box to validate syntax without executing actions.
      box = ::Ruby::Box.new
      box.eval(source)
      source
    rescue SyntaxError => error
      raise Error, "Invalid generated frontend: #{error.message}"
    rescue SystemCallError => error
      raise Error, "Cannot read Ruby frontend inputs: #{error.message}"
    end
  end
end
