module Lrama
  module Ruby
    VERSION: String

    class Error < StandardError
    end

    def self.generate: (String source, ?filename: String, ?class_name: String) -> String
    def self.compile: (String source, ?filename: String, ?class_name: String) -> Class

    class Generator
      def initialize: () -> void
      def generate: (String source, ?filename: String, ?class_name: String) -> String
    end
  end
end
