module Lrama
  module Ruby
    VERSION: String

    class Error < StandardError
    end

    def self.generate: (String source, ?filename: String, ?class_name: String, ?mode: (:parser | :recognizer)) -> String
    def self.compile: (String source, ?filename: String, ?class_name: String, ?mode: (:parser | :recognizer)) -> Class

    class Generator
      def initialize: () -> void
      def generate: (String source, ?filename: String, ?class_name: String, ?mode: (:parser | :recognizer)) -> String
    end
  end
end
