# frozen_string_literal: true

# Rule IDs refer to upstream_rules.json, validated against the pinned source.
# Each entry is [classification, Ruby expression used as the reduction value].
module RubyGrammarActions
  ACTIONS = {
    1 => ["empty", "nil"], 2 => ["empty", "nil"], 3 => ["empty", "nil"],
    4 => ["pass_through", "$1"], 5 => ["ported", "@builder.program($2)"],
    83 => ["pass_through", "$1"], 84 => ["pass_through", "$1"],
    86 => ["empty", "nil"], 87 => ["empty", "nil"],
    6 => ["ported", "[].freeze"], 7 => ["ported", "[$1].freeze"],
    8 => ["ported", "($1 + [$3]).freeze"], 9 => ["pass_through", "$1"],
    13 => ["pass_through", "$1"], 19 => ["ported", "[].freeze"],
    20 => ["ported", "[$1].freeze"], 21 => ["ported", "($1 + [$3]).freeze"],
    22 => ["pass_through", "$1"], 45 => ["pass_through", "$1"],
    25 => ["empty", "nil"],
    63 => ["empty", "nil"], 64 => ["pass_through", "nil"],
    78 => ["pass_through", "$1"], 140 => ["ported", "@builder.declare_local($1)"],
    154 => ["pass_through", "$1"],
    88 => ["pass_through", "$2"],
    372 => ["ported", "@builder.loop(:while, $2, $3)"],
    373 => ["ported", "@builder.loop(:until, $2, $3)"],
    392 => ["ported", "@builder.control(:break)"],
    393 => ["ported", "@builder.control(:next)"],
    394 => ["ported", "@builder.control(:redo)"],
    395 => ["ported", "@builder.control(:retry)"],
    359 => ["ported", "@builder.control(:return)"],
    235 => ["ported", "@builder.assign($1, $4)"], 236 => ["pass_through", "$1"],
    246 => ["ported", "@builder.range(:\"..\", $1, $3)"],
    247 => ["ported", "@builder.range(:\"...\", $1, $3)"],
    252 => ["pass_through", "$1"],
    284 => ["ported", "@builder.ternary($1, $3, $6)"],
    96 => ["pass_through", "$1"],
    305 => ["pass_through", "$2"],
    308 => ["empty", "nil"], 309 => ["pass_through", "$1"],
    310 => ["empty", "nil"], 311 => ["pass_through", "$1"],
    312 => ["pass_through", "$1"],
    327 => ["empty", "nil"],
    318 => ["pass_through", "$1"],
    507 => ["ported", "@builder.call($1, $2 || [])"],
    367 => ["pass_through", "$1"],
    396 => ["pass_through", "$1"], 397 => ["pass_through", "$1"],
    401 => ["pass_through", "nil"], 402 => ["pass_through", "nil"],
    423 => ["pass_through", "nil"],
    417 => ["pass_through", "nil"],
    340 => ["pass_through", "$1"],
    639 => ["pass_through", "$1"],
    638 => ["pass_through", "$1"],
    514 => ["ported", "@builder.index($1, $3 || [])"],
    643 => ["ported", "@builder.string(@builder.join_strings($2))"],
    641 => ["pass_through", "$1"],
    642 => ["ported", "@builder.concat_strings($1, $2)"],
    666 => ["empty", "[]"], 667 => ["ported", "($1 + [$2]).freeze"],
    672 => ["pass_through", "$1"],
    345 => ["pass_through", "$1"],
    684 => ["pass_through", "$1"], 685 => ["pass_through", "$1"],
    686 => ["ported", "@builder.symbol($2)"],
    687 => ["pass_through", "$1"], 688 => ["pass_through", "$1"],
    253 => ["ported", "@builder.binary(:+, $1, $3)"],
    254 => ["ported", "@builder.binary(:-, $1, $3)"],
    255 => ["ported", "@builder.binary(:*, $1, $3)"],
    256 => ["ported", "@builder.binary(:/, $1, $3)"],
    257 => ["ported", "@builder.binary(:%, $1, $3)"],
    262 => ["ported", "@builder.binary(:\"|\", $1, $3)"],
    263 => ["ported", "@builder.binary(:\"^\", $1, $3)"],
    264 => ["ported", "@builder.binary(:\"&\", $1, $3)"],
    265 => ["ported", "@builder.binary(:\"<=>\", $1, $3)"],
    266 => ["pass_through", "$1"],
    267 => ["ported", "@builder.binary(:\"==\", $1, $3)"],
    268 => ["ported", "@builder.binary(:\"===\", $1, $3)"],
    269 => ["ported", "@builder.binary(:\"!=\", $1, $3)"],
    270 => ["ported", "@builder.binary(:\"=~\", $1, $3)"],
    271 => ["ported", "@builder.binary(:\"!~\", $1, $3)"],
    272 => ["ported", "@builder.unary(:\"!\", $2)"],
    273 => ["ported", "@builder.unary(:\"~\", $2)"],
    274 => ["ported", "@builder.binary(:\"<<\", $1, $3)"],
    275 => ["ported", "@builder.binary(:\">>\", $1, $3)"],
    276 => ["ported", "@builder.binary(:\"&&\", $1, $3)"],
    277 => ["ported", "@builder.binary(:\"||\", $1, $3)"],
    282 => ["pass_through", "$1"],
    288 => ["ported", "@builder.operator(\">\")"], 289 => ["ported", "@builder.operator(\"<\")"],
    290 => ["ported", "@builder.operator(\">=\")"], 291 => ["ported", "@builder.operator(\"<=\")"],
    292 => ["ported", "@builder.binary($2, $1, $3)"],
    293 => ["ported", "@builder.binary($2, $1, $3)"],
    260 => ["ported", "@builder.unary(:+, $2)"],
    261 => ["ported", "@builder.unary(:-, $2)"],
    283 => ["pass_through", "$1"], 294 => ["empty", "nil"],
    297 => ["pass_through", "$1"], 303 => ["pass_through", "$1"],
    339 => ["pass_through", "$1"],
    354 => ["ported", "@builder.parentheses($2, 354)"],
    637 => ["pass_through", "$1"], 690 => ["pass_through", "$1"],
    691 => ["ported", "@builder.unary(:-, $2)"],
    692 => ["ported", "@builder.integer($1)"], 693 => ["ported", "@builder.float($1)"],
    640 => ["ported", "@builder.literal($1)"],
    694 => ["ported", "@builder.literal($1)"],
    695 => ["ported", "@builder.literal($1)"],
    699 => ["ported", "@builder.identifier($1)"],
    700 => ["ported", "@builder.variable(:constant, $1)"],
    702 => ["ported", "@builder.literal(nil)"],
    703 => ["ported", "@builder.literal(:self)"],
    696 => ["ported", "@builder.variable(:instance, $1)"],
    697 => ["ported", "@builder.variable(:global, $1)"],
    698 => ["ported", "@builder.variable(:class, $1)"],
    701 => ["pass_through", "$1"],
    704 => ["ported", "@builder.literal(true)"], 705 => ["ported", "@builder.literal(false)"],
    709 => ["ported", "@builder.read_local($1)"], 710 => ["pass_through", "$1"],
    849 => ["empty", "nil"], 850 => ["empty", "nil"], 851 => ["empty", "nil"],
    852 => ["empty", "nil"], 853 => ["empty", "nil"],
    298 => ["pass_through", "$1"],
    299 => ["ported", "[].freeze"],
    300 => ["pass_through", "$1"],
    301 => ["ported", "($1 + $3).freeze"],
    302 => ["pass_through", "$1"],
    328 => ["ported", "[$1].freeze"],
    330 => ["ported", "($1 + [$3]).freeze"],
    347 => ["pass_through", "$1"],
    357 => ["ported", "@builder.array($2)"],
    358 => ["ported", "@builder.hash($2)"],
    821 => ["ported", "[].freeze"],
    822 => ["pass_through", "$1"],
    823 => ["ported", "[$1].freeze"],
    824 => ["ported", "($1 + [$3]).freeze"],
    825 => ["ported", "@builder.pair($1, $3)"],
    826 => ["ported", "@builder.pair(@builder.symbol($1), $2)"],
    847 => ["pass_through", "nil"],
    848 => ["pass_through", "nil"],
    844 => ["pass_through", "nil"],
    845 => ["pass_through", "nil"],
    370 => ["ported", "@builder.if_node($2, $4, $5)"],
    371 => ["ported", "@builder.unless_node($2, $4, $5)"],
    399 => ["pass_through", "nil"], 400 => ["pass_through", "nil"],
    413 => ["pass_through", "nil"], 414 => ["pass_through", "nil"],
    415 => ["pass_through", "nil"],
    419 => ["pass_through", "nil"], 420 => ["pass_through", "nil"],
    421 => ["pass_through", "nil"],
    424 => ["pass_through", "$1"],
    425 => ["ported", "@builder.elsif_node($2, $4, $5)"],
    426 => ["empty", "nil"], 427 => ["pass_through", "$2"]
  }.freeze
end
