# frozen_string_literal: true

# Rule IDs refer to upstream_rules.json, validated against the pinned source.
# Each entry is [classification, Ruby expression used as the reduction value].
module RubyGrammarActions
  ACTIONS = {
    1 => ["empty", "nil"], 2 => ["empty", "nil"], 3 => ["empty", "nil"],
    4 => ["pass_through", "$1"], 5 => ["ported", "@builder.program($2)"],
    11 => ["empty", "nil"], 14 => ["empty", "nil"], 15 => ["empty", "nil"],
    23 => ["empty", "nil"], 27 => ["empty", "nil"], 39 => ["pass_through", "$1"],
    42 => ["pass_through", "$1"],
    48 => ["pass_through", "$1"], 57 => ["pass_through", "$1"],
    60 => ["pass_through", "$1"], 61 => ["pass_through", "$1"],
    66 => ["pass_through", "$1"], 68 => ["pass_through", "$1"],
    74 => ["empty", "nil"],
    76 => ["empty", "nil"], 81 => ["empty", "nil"],
    90 => ["pass_through", "$1"], 91 => ["pass_through", "$1"],
    92 => ["pass_through", "$1"], 93 => ["pass_through", "$1"],
    97 => ["pass_through", "$1"], 98 => ["pass_through", "$1"],
    111 => ["pass_through", "$1"], 113 => ["pass_through", "$1"],
    115 => ["pass_through", "$1"], 118 => ["pass_through", "$1"],
    125 => ["empty", "nil"], 127 => ["pass_through", "$1"],
    131 => ["pass_through", "$1"], 132 => ["pass_through", "$1"],
    139 => ["pass_through", "$1"], 141 => ["pass_through", "$1"],
    148 => ["pass_through", "$1"], 155 => ["pass_through", "$1"],
    156 => ["pass_through", "$1"], 157 => ["pass_through", "$1"],
    158 => ["pass_through", "$1"], 159 => ["pass_through", "$1"],
    160 => ["pass_through", "$1"], 161 => ["pass_through", "$1"],
    162 => ["empty", "nil"],
    164 => ["ported", "@builder.operator(\"|\")"], 165 => ["ported", "@builder.operator(\"^\")"],
    166 => ["ported", "@builder.operator(\"&\")"], 167 => ["ported", "@builder.operator(\"<=>\")"],
    168 => ["ported", "@builder.operator(\"==\")"],
    169 => ["ported", "@builder.operator(\"===\")"], 170 => ["ported", "@builder.operator(\"=~\")"],
    171 => ["ported", "@builder.operator(\"!~\")"], 172 => ["ported", "@builder.operator(\">\")"],
    173 => ["ported", "@builder.operator(\">=\")"], 174 => ["ported", "@builder.operator(\"<\")"],
    175 => ["ported", "@builder.operator(\"<=\")"], 176 => ["ported", "@builder.operator(\"!=\")"],
    177 => ["ported", "@builder.operator(\"<<\")"], 178 => ["ported", "@builder.operator(\">>\")"],
    179 => ["ported", "@builder.operator(\"+\")"], 180 => ["ported", "@builder.operator(\"-\")"],
    181 => ["ported", "@builder.operator(\"*\")"], 182 => ["ported", "@builder.operator(\"*\")"],
    183 => ["ported", "@builder.operator(\"/\")"], 184 => ["ported", "@builder.operator(\"%\")"],
    185 => ["ported", "@builder.operator(\"**\")"], 186 => ["ported", "@builder.operator(\"**\")"],
    187 => ["ported", "@builder.operator(\"!\")"], 188 => ["ported", "@builder.operator(\"~\")"],
    189 => ["ported", "@builder.operator(\"+@\")"], 190 => ["ported", "@builder.operator(\"-@\")"],
    191 => ["ported", "@builder.operator(\"[]\")"], 192 => ["ported", "@builder.operator(\"[]=\")"],
    193 => ["ported", "@builder.operator(\"`\")"],
    194 => ["ported", "@builder.reserved_word(\"__LINE__\")"],
    195 => ["ported", "@builder.reserved_word(\"__FILE__\")"],
    196 => ["ported", "@builder.reserved_word(\"__ENCODING__\")"],
    197 => ["ported", "@builder.reserved_word(\"BEGIN\")"],
    198 => ["ported", "@builder.reserved_word(\"END\")"],
    199 => ["ported", "@builder.reserved_word(\"alias\")"],
    200 => ["ported", "@builder.reserved_word(\"and\")"],
    201 => ["ported", "@builder.reserved_word(\"begin\")"],
    202 => ["ported", "@builder.reserved_word(\"break\")"],
    203 => ["ported", "@builder.reserved_word(\"case\")"],
    204 => ["ported", "@builder.reserved_word(\"class\")"],
    205 => ["ported", "@builder.reserved_word(\"def\")"],
    206 => ["ported", "@builder.reserved_word(\"defined?\")"],
    207 => ["ported", "@builder.reserved_word(\"do\")"],
    208 => ["ported", "@builder.reserved_word(\"else\")"],
    209 => ["ported", "@builder.reserved_word(\"elsif\")"],
    210 => ["ported", "@builder.reserved_word(\"end\")"],
    211 => ["ported", "@builder.reserved_word(\"ensure\")"],
    212 => ["ported", "@builder.reserved_word(\"false\")"],
    213 => ["ported", "@builder.reserved_word(\"for\")"],
    214 => ["ported", "@builder.reserved_word(\"in\")"],
    215 => ["ported", "@builder.reserved_word(\"module\")"],
    216 => ["ported", "@builder.reserved_word(\"next\")"],
    217 => ["ported", "@builder.reserved_word(\"nil\")"],
    218 => ["ported", "@builder.reserved_word(\"not\")"],
    219 => ["ported", "@builder.reserved_word(\"or\")"],
    220 => ["ported", "@builder.reserved_word(\"redo\")"],
    221 => ["ported", "@builder.reserved_word(\"rescue\")"],
    222 => ["ported", "@builder.reserved_word(\"retry\")"],
    223 => ["ported", "@builder.reserved_word(\"return\")"],
    224 => ["ported", "@builder.reserved_word(\"self\")"],
    225 => ["ported", "@builder.reserved_word(\"super\")"],
    226 => ["ported", "@builder.reserved_word(\"then\")"],
    227 => ["ported", "@builder.reserved_word(\"true\")"],
    228 => ["ported", "@builder.reserved_word(\"undef\")"],
    229 => ["ported", "@builder.reserved_word(\"when\")"],
    230 => ["ported", "@builder.reserved_word(\"yield\")"],
    231 => ["ported", "@builder.reserved_word(\"if\")"],
    232 => ["ported", "@builder.reserved_word(\"unless\")"],
    233 => ["ported", "@builder.reserved_word(\"while\")"],
    234 => ["ported", "@builder.reserved_word(\"until\")"],
    83 => ["pass_through", "$1"], 84 => ["pass_through", "$1"],
    86 => ["empty", "nil"], 87 => ["empty", "nil"],
    6 => ["ported", "[].freeze"], 7 => ["ported", "[$1].freeze"],
    8 => ["ported", "($1 + [$3]).freeze"], 9 => ["pass_through", "$1"],
    13 => ["pass_through", "$1"], 19 => ["ported", "[].freeze"],
    20 => ["ported", "[$1].freeze"], 21 => ["ported", "($1 + [$3]).freeze"],
    22 => ["pass_through", "$1"], 45 => ["pass_through", "$1"],
    25 => ["empty", "nil"],
    63 => ["empty", "nil"], 64 => ["pass_through", "nil"],
    70 => ["ported", "@builder.binary(:and, $1, $3)"],
    69 => ["pass_through", "$1"],
    72 => ["ported", "@builder.unary(:\"!\", $3)"],
    287 => ["ported", "@builder.unary(:\"!\", $3)"],
    71 => ["ported", "@builder.binary(:or, $1, $3)"],
    108 => ["ported", "@builder.call(:return, $2 || [])"],
    107 => ["ported", "@builder.call(:yield, $2 || [])"],
    106 => ["ported", "@builder.call(:super, $2 || [])"],
    99 => ["ported", "@builder.call($1, $2 || [])"],
    33 => ["ported", "@builder.if_node($3, [$1], nil)"],
    34 => ["ported", "@builder.unless_node($3, [$1], nil)"],
    35 => ["ported", "@builder.loop(:while, $3, [$1])"],
    36 => ["ported", "@builder.loop(:until, $3, [$1])"],
    37 => ["ported", "@builder.rescue_modifier($1, $4)"],
    374 => ["empty", "nil"], 376 => ["empty", "nil"],
    375 => ["ported", "@builder.case_node($2, @builder.case_parts($5).first, @builder.case_parts($5).last)"],
    377 => ["ported", "@builder.case_node(@builder.literal(nil), @builder.case_parts($4).first, @builder.case_parts($4).last)"],
    521 => ["ported", "[$1].freeze"],
    523 => ["ported", "($1 + [$3]).freeze"],
    525 => ["ported", "@builder.case_chain(@builder.when_node($2, $4), $5)"],
    526 => ["pass_through", "$1"],
    527 => ["ported", "[$1].freeze"],
    412 => ["pass_through", "nil"],
    419 => ["pass_through", "nil"], 420 => ["pass_through", "nil"], 421 => ["pass_through", "nil"],
    426 => ["empty", "nil"],
    550 => ["pass_through", "$2"],
    539 => ["pass_through", "$1"],
    522 => ["pass_through", "$2"], 427 => ["pass_through", "$2"],
    630 => ["pass_through", "$1"], 631 => ["pass_through", "$1"],
    632 => ["empty", "nil"], 633 => ["pass_through", "$2"], 634 => ["empty", "nil"],
    635 => ["pass_through", "$2"],
    245 => ["pass_through", "$1"], 285 => ["pass_through", "$1"],
    315 => ["pass_through", "$1"], 316 => ["pass_through", "$1"],
    317 => ["pass_through", "$1"],
    321 => ["pass_through", "$1"], 325 => ["empty", "nil"],
    329 => ["pass_through", "$1"], 333 => ["empty", "nil"],
    334 => ["pass_through", "$1"],
    335 => ["pass_through", "$1"], 350 => ["empty", "nil"],
    352 => ["empty", "nil"], 390 => ["empty", "nil"],
    296 => ["pass_through", "nil"],
    109 => ["ported", "@builder.call(:break, $2 || [])"],
    110 => ["ported", "@builder.call(:next, $2 || [])"],
    89 => ["pass_through", "$1"],
    78 => ["pass_through", "$1"], 140 => ["ported", "@builder.declare_local($1)"],
    154 => ["pass_through", "$1"],
    88 => ["pass_through", "$2"],
    372 => ["ported", "@builder.loop(:while, $2, $3)"],
    373 => ["ported", "@builder.loop(:until, $2, $3)"],
    392 => ["ported", "@builder.control(:break)"],
    393 => ["ported", "@builder.control(:next)"],
    394 => ["ported", "@builder.control(:redo)"],
    395 => ["ported", "@builder.control(:retry)"],
    359 => ["ported", "@builder.control(:return)"],
    235 => ["ported", "@builder.assign($1, $4)"], 236 => ["pass_through", "$1"],
    246 => ["ported", "@builder.range(:\"..\", $1, $3)"],
    247 => ["ported", "@builder.range(:\"...\", $1, $3)"],
    248 => ["ported", "@builder.range(:\"..\", $1, nil)"],
    249 => ["ported", "@builder.range(:\"...\", $1, nil)"],
    250 => ["ported", "@builder.range(:\"..\", nil, $2)"],
    251 => ["ported", "@builder.range(:\"...\", nil, $2)"],
    258 => ["ported", "@builder.binary(:\"**\", $1, $3)"],
    259 => ["ported", "@builder.binary(:\"**\", @builder.unary(:-@, $2), $4)"],
    306 => ["ported", "($2 + [$4]).freeze"],
    307 => ["pass_through", "$2"],
    319 => ["pass_through", "$1"],
    320 => ["ported", "(($1 || []) + ($3 || [])).freeze"],
    324 => ["pass_through", "$2"],
    326 => ["pass_through", "$2"],
    331 => ["ported", "($1 + [$3]).freeze"],
    332 => ["pass_through", "$2"],
    336 => ["ported", "($1 + [$3]).freeze"],
    337 => ["ported", "($1 + [$4]).freeze"],
    338 => ["ported", "[$2].freeze"],
    349 => ["ported", "@builder.reserved_word(\"method\")"],
    16 => ["ported", "@builder.body_nodes($1)"],
    43 => ["ported", "@builder.assign($1, @builder.rescue_modifier($4, $7))"],
    281 => ["pass_through", "$1"],
    416 => ["empty", "nil"],
    439 => ["pass_through", "$2"],
    449 => ["pass_through", "$2"],
    460 => ["pass_through", "$2"],
    515 => ["pass_through", "$2"],
    133 => ["ported", "@builder.index($1, $3 || [])"],
    138 => ["ported", "@builder.variable(:constant, $2)"],
    147 => ["ported", "@builder.variable(:constant, $2)"],
    286 => ["ported", "@builder.rescue_modifier($1, $4)"],
    112 => ["pass_through", "$2"],
    163 => ["ported", "($1 + [$4]).freeze"],
    351 => ["ported", "@builder.body_nodes($3)"],
    114 => ["pass_through", "$2"],
    128 => ["pass_through", "$2"],
    129 => ["ported", "[$1].freeze"],
    116 => ["ported", "($1 + [$2]).freeze"],
    117 => ["ported", "($1 + [$3]).freeze"],
    119 => ["ported", "($1 + [$3]).freeze"],
    120 => ["ported", "($1 + [$3] + $5).freeze"],
    122 => ["pass_through", "$1"],
    121 => ["pass_through", "$1"],
    123 => ["pass_through", "$2"],
    124 => ["pass_through", "$2"],
    126 => ["pass_through", "$3"],
    130 => ["ported", "($1 + [$2]).freeze"],
    304 => ["ported", "@builder.rescue_modifier($1, $4)"],
    46 => ["empty", "nil"],
    85 => ["empty", "nil"],
    252 => ["pass_through", "$1"],
    284 => ["ported", "@builder.ternary($1, $3, $6)"],
    96 => ["pass_through", "$1"],
    305 => ["pass_through", "$2"],
    308 => ["empty", "nil"], 309 => ["pass_through", "$1"],
    310 => ["empty", "nil"], 311 => ["pass_through", "$1"],
    312 => ["pass_through", "$1"],
    327 => ["empty", "nil"],
    318 => ["pass_through", "$1"],
    322 => ["empty", "nil"],
    323 => ["pass_through", "$2"],
    507 => ["ported", "@builder.call($1, $2 || [])"],
    367 => ["pass_through", "$1"],
    396 => ["pass_through", "$1"], 397 => ["pass_through", "$1"],
    401 => ["pass_through", "nil"], 402 => ["pass_through", "nil"],
    403 => ["pass_through", "nil"],
    423 => ["pass_through", "nil"],
    417 => ["pass_through", "nil"],
    418 => ["pass_through", "nil"],
    360 => ["ported", "@builder.call(:yield, $3 || [])"],
    361 => ["ported", "@builder.call(:yield, [])"],
    362 => ["ported", "@builder.call(:yield, [])"],
    512 => ["ported", "@builder.call(:super, $2 || [])"],
    513 => ["ported", "@builder.call(:super, [])"],
    364 => ["ported", "@builder.unary(:\"!\", $3)"],
    295 => ["pass_through", "nil"],
    363 => ["ported", "@builder.call(:defined, [$5])"],
    278 => ["ported", "@builder.call(:defined, [$4])"],
    340 => ["pass_through", "$1"],
    343 => ["ported", "@builder.word_array($1)"],
    344 => ["ported", "@builder.word_array($1, symbols: true)"],
    496 => ["pass_through", "$2"], 785 => ["pass_through", "$1"],
    346 => ["pass_through", "$1"],
    611 => ["pass_through", "$1"], 612 => ["pass_through", "$1"],
    613 => ["pass_through", "$1"], 614 => ["pass_through", "$1"],
    615 => ["pass_through", "$1"], 616 => ["pass_through", "$1"],
    646 => ["pass_through", "nil"], 647 => ["pass_through", "nil"],
    648 => ["pass_through", "$3"], 649 => ["pass_through", "$1"],
    650 => ["empty", "[]"], 651 => ["ported", "($1 + [$2]).freeze"],
    652 => ["pass_through", "$1"], 653 => ["ported", "$1.to_s + $2.to_s"],
    654 => ["pass_through", "$3"], 655 => ["ported", "@builder.word_array($1, symbols: true)"],
    656 => ["empty", "[]"], 657 => ["ported", "($1 + [$2]).freeze"],
    658 => ["pass_through", "$3"], 659 => ["ported", "@builder.word_array($1)"],
    660 => ["pass_through", "$3"], 661 => ["ported", "@builder.word_array($1, symbols: true)"],
    662 => ["empty", "[]"], 663 => ["ported", "($1 + [$2]).freeze"],
    342 => ["pass_through", "$1"],
    341 => ["pass_through", "$1"],
    379 => ["empty", "nil"], 380 => ["empty", "nil"],
    381 => ["ported", "@builder.for_node($2, $5, $8)"],
    404 => ["pass_through", "nil"], 428 => ["pass_through", "$1"],
    644 => ["ported", "@builder.xstring(@builder.join_strings($2))"],
    668 => ["empty", "[]"], 669 => ["ported", "($1 + [$2]).freeze"],
    645 => ["ported", "@builder.regexp(@builder.join_strings($2))"],
    670 => ["empty", "[]"], 671 => ["ported", "($1 + [$2]).freeze"],
    639 => ["pass_through", "$1"],
    638 => ["pass_through", "$1"],
    514 => ["ported", "@builder.index($1, $3 || [])"],
    643 => ["ported", "@builder.string(@builder.join_strings($2))"],
    641 => ["pass_through", "$1"],
    642 => ["ported", "@builder.concat_strings($1, $2)"],
    666 => ["empty", "[]"], 667 => ["ported", "($1 + [$2]).freeze"],
    672 => ["pass_through", "$1"],
    345 => ["pass_through", "$1"],
    684 => ["pass_through", "$1"], 685 => ["pass_through", "$1"],
    686 => ["ported", "@builder.symbol($2)"],
    687 => ["pass_through", "$1"], 688 => ["pass_through", "$1"],
    253 => ["ported", "@builder.binary(:+, $1, $3)"],
    254 => ["ported", "@builder.binary(:-, $1, $3)"],
    255 => ["ported", "@builder.binary(:*, $1, $3)"],
    256 => ["ported", "@builder.binary(:/, $1, $3)"],
    257 => ["ported", "@builder.binary(:%, $1, $3)"],
    262 => ["ported", "@builder.binary(:\"|\", $1, $3)"],
    263 => ["ported", "@builder.binary(:\"^\", $1, $3)"],
    264 => ["ported", "@builder.binary(:\"&\", $1, $3)"],
    265 => ["ported", "@builder.binary(:\"<=>\", $1, $3)"],
    266 => ["pass_through", "$1"],
    267 => ["ported", "@builder.binary(:\"==\", $1, $3)"],
    268 => ["ported", "@builder.binary(:\"===\", $1, $3)"],
    269 => ["ported", "@builder.binary(:\"!=\", $1, $3)"],
    270 => ["ported", "@builder.binary(:\"=~\", $1, $3)"],
    271 => ["ported", "@builder.binary(:\"!~\", $1, $3)"],
    272 => ["ported", "@builder.unary(:\"!\", $2)"],
    273 => ["ported", "@builder.unary(:\"~\", $2)"],
    274 => ["ported", "@builder.binary(:\"<<\", $1, $3)"],
    275 => ["ported", "@builder.binary(:\">>\", $1, $3)"],
    276 => ["ported", "@builder.binary(:\"&&\", $1, $3)"],
    277 => ["ported", "@builder.binary(:\"||\", $1, $3)"],
    282 => ["pass_through", "$1"],
    288 => ["ported", "@builder.operator(\">\")"], 289 => ["ported", "@builder.operator(\"<\")"],
    290 => ["ported", "@builder.operator(\">=\")"], 291 => ["ported", "@builder.operator(\"<=\")"],
    292 => ["ported", "@builder.binary($2, $1, $3)"],
    293 => ["ported", "@builder.binary($2, $1, $3)"],
    260 => ["ported", "@builder.unary(:+, $2)"],
    261 => ["ported", "@builder.unary(:-, $2)"],
    283 => ["pass_through", "$1"], 294 => ["empty", "nil"],
    297 => ["pass_through", "$1"], 303 => ["pass_through", "$1"],
    339 => ["pass_through", "$1"],
    353 => ["ported", "@builder.parentheses($2, 353)"],
    354 => ["ported", "@builder.parentheses($2, 354)"],
    637 => ["pass_through", "$1"], 690 => ["pass_through", "$1"],
    691 => ["ported", "@builder.unary(:-, $2)"],
    692 => ["ported", "@builder.integer($1)"], 693 => ["ported", "@builder.float($1)"],
    640 => ["ported", "@builder.literal($1)"],
    617 => ["pass_through", "$1"], 618 => ["pass_through", "$1"],
    694 => ["ported", "@builder.literal($1)"],
    695 => ["ported", "@builder.literal($1)"],
    699 => ["ported", "@builder.identifier($1)"],
    700 => ["ported", "@builder.variable(:constant, $1)"],
    702 => ["ported", "@builder.literal(nil)"],
    703 => ["ported", "@builder.literal(:self)"],
    706 => ["ported", "@builder.literal(:__FILE__)"],
    707 => ["ported", "@builder.literal(:__LINE__)"],
    708 => ["ported", "@builder.literal(:__ENCODING__)"],
    713 => ["ported", "@builder.variable(:backref, $1)"],
    714 => ["ported", "@builder.variable(:backref, $1)"],
    348 => ["pass_through", "$1"],
    696 => ["ported", "@builder.variable(:instance, $1)"],
    697 => ["ported", "@builder.variable(:global, $1)"],
    698 => ["ported", "@builder.variable(:class, $1)"],
    701 => ["pass_through", "$1"],
    704 => ["ported", "@builder.literal(true)"], 705 => ["ported", "@builder.literal(false)"],
    709 => ["ported", "@builder.read_local($1)"], 710 => ["pass_through", "$1"],
    849 => ["empty", "nil"], 850 => ["empty", "nil"], 851 => ["empty", "nil"],
    852 => ["empty", "nil"], 853 => ["empty", "nil"],
    298 => ["pass_through", "$1"],
    299 => ["ported", "[].freeze"],
    300 => ["pass_through", "$1"],
    301 => ["ported", "($1 + $3).freeze"],
    302 => ["pass_through", "$1"],
    328 => ["ported", "[$1].freeze"],
    330 => ["ported", "($1 + [$3]).freeze"],
    347 => ["pass_through", "$1"],
    357 => ["ported", "@builder.array($2)"],
    358 => ["ported", "@builder.hash($2)"],
    821 => ["ported", "[].freeze"],
    822 => ["pass_through", "$1"],
    823 => ["ported", "[$1].freeze"],
    824 => ["ported", "($1 + [$3]).freeze"],
    825 => ["ported", "@builder.pair($1, $3)"],
    826 => ["ported", "@builder.pair(@builder.symbol($1), $2)"],
    847 => ["pass_through", "nil"],
    848 => ["pass_through", "nil"],
    844 => ["pass_through", "nil"],
    845 => ["pass_through", "nil"],
    370 => ["ported", "@builder.if_node($2, $4, $5)"],
    371 => ["ported", "@builder.unless_node($2, $4, $5)"],
    399 => ["pass_through", "nil"], 400 => ["pass_through", "nil"],
    413 => ["pass_through", "nil"], 414 => ["pass_through", "nil"],
    415 => ["pass_through", "nil"],
    419 => ["pass_through", "nil"], 420 => ["pass_through", "nil"],
    421 => ["pass_through", "nil"],
    424 => ["pass_through", "$1"],
    425 => ["ported", "@builder.elsif_node($2, $4, $5)"],
    426 => ["empty", "nil"], 427 => ["pass_through", "$2"],
    17 => ["empty", "nil"], 18 => ["ported", "@builder.body_nodes($1)"],
    79 => ["pass_through", "$1"], 80 => ["pass_through", "$2"], 407 => ["empty", "nil"],
    388 => ["empty", "nil"],
    720 => ["empty", "nil"], 721 => ["pass_through", "$2"],
    722 => ["pass_through", "$1"], 723 => ["empty", "nil"], 724 => ["pass_through", "$2"],
    764 => ["empty", "[]"], 765 => ["pass_through", "$1"],
    389 => ["ported", "@builder.def_node($1, $2, @builder.body_nodes($4))"],
    629 => ["empty", "nil"], 636 => ["empty", "nil"],
    149 => ["pass_through", "$1"], 150 => ["pass_through", "$1"],
    151 => ["pass_through", "$2"], 152 => ["pass_through", "$1"], 153 => ["pass_through", "$2"],
    382 => ["empty", "nil"], 384 => ["empty", "nil"], 386 => ["empty", "nil"],
    383 => ["ported", "@builder.class_node($2, $3, $5)"],
    387 => ["ported", "@builder.module_node($2, $4)"],
    405 => ["empty", "nil"], 406 => ["empty", "nil"],
    408 => ["empty", "nil"], 410 => ["empty", "nil"], 411 => ["empty", "nil"],
    422 => ["pass_through", "$1"], 429 => ["pass_through", "$1"],
    430 => ["pass_through", "$1"],
    432 => ["pass_through", "$1"], 434 => ["pass_through", "$1"],
    437 => ["pass_through", "$1"], 440 => ["empty", "nil"],
    441 => ["pass_through", "$1"], 442 => ["pass_through", "$1"],
    443 => ["empty", "nil"], 446 => ["pass_through", "$1"],
    447 => ["pass_through", "$1"], 450 => ["empty", "nil"],
    454 => ["pass_through", "$1"], 455 => ["pass_through", "$1"],
    456 => ["empty", "nil"], 458 => ["pass_through", "$1"],
    461 => ["empty", "nil"], 474 => ["pass_through", "$1"],
    477 => ["pass_through", "$1"], 478 => ["pass_through", "$1"],
    479 => ["empty", "nil"],
    480 => ["pass_through", "$1"], 482 => ["empty", "nil"],
    483 => ["pass_through", "$1"], 484 => ["pass_through", "$1"],
    486 => ["pass_through", "$1"], 489 => ["pass_through", "$1"],
    490 => ["empty", "nil"], 491 => ["empty", "nil"], 492 => ["empty", "nil"],
    497 => ["pass_through", "$1"], 517 => ["empty", "nil"], 519 => ["empty", "nil"],
    528 => ["empty", "nil"], 529 => ["empty", "nil"], 530 => ["empty", "nil"],
    531 => ["empty", "nil"], 533 => ["pass_through", "$1"], 534 => ["pass_through", "$1"],
    535 => ["pass_through", "$1"], 538 => ["pass_through", "$1"],
    541 => ["pass_through", "$1"], 542 => ["pass_through", "$1"],
    543 => ["pass_through", "$1"], 544 => ["pass_through", "$1"],
    546 => ["pass_through", "$1"], 547 => ["empty", "nil"],
    549 => ["pass_through", "$1"], 552 => ["pass_through", "$1"],
    553 => ["pass_through", "$1"], 565 => ["empty", "nil"],
    569 => ["pass_through", "$1"], 570 => ["pass_through", "$1"],
    574 => ["pass_through", "$1"], 577 => ["pass_through", "$1"],
    581 => ["empty", "nil"],
    582 => ["pass_through", "$1"], 584 => ["pass_through", "$1"],
    586 => ["pass_through", "$1"], 588 => ["pass_through", "$1"],
    589 => ["pass_through", "$1"], 592 => ["pass_through", "$1"],
    593 => ["pass_through", "$1"], 596 => ["empty", "nil"],
    598 => ["pass_through", "$1"], 599 => ["pass_through", "$1"],
    600 => ["pass_through", "$1"], 607 => ["pass_through", "$1"],
    608 => ["pass_through", "$1"], 609 => ["pass_through", "$1"],
    610 => ["pass_through", "$1"],
    619 => ["pass_through", "$1"], 627 => ["pass_through", "$1"],
    664 => ["empty", "nil"], 673 => ["empty", "nil"], 675 => ["empty", "nil"],
    676 => ["empty", "nil"], 677 => ["empty", "nil"], 678 => ["empty", "nil"],
    680 => ["empty", "nil"], 681 => ["empty", "nil"], 682 => ["pass_through", "$1"],
    683 => ["pass_through", "$1"], 711 => ["pass_through", "$1"],
    712 => ["pass_through", "$1"], 715 => ["empty", "nil"],
    718 => ["pass_through", "$1"], 719 => ["empty", "nil"],
    726 => ["pass_through", "$1"], 727 => ["pass_through", "$1"],
    730 => ["pass_through", "$1"], 734 => ["pass_through", "$1"],
    735 => ["pass_through", "$1"], 736 => ["pass_through", "$1"],
    740 => ["pass_through", "$1"], 741 => ["pass_through", "$1"],
    742 => ["pass_through", "$1"],
    744 => ["pass_through", "$1"], 747 => ["pass_through", "$1"],
    760 => ["pass_through", "$1"], 762 => ["pass_through", "$1"],
    763 => ["pass_through", "$1"], 767 => ["empty", "nil"],
    780 => ["pass_through", "$1"], 782 => ["pass_through", "$1"],
    783 => ["pass_through", "$1"], 784 => ["empty", "nil"],
    786 => ["empty", "nil"], 787 => ["pass_through", "$1"],
    791 => ["pass_through", "$1"],
    793 => ["pass_through", "$1"], 794 => ["pass_through", "$1"],
    796 => ["pass_through", "$1"], 798 => ["pass_through", "$1"],
    799 => ["empty", "nil"], 800 => ["empty", "nil"], 801 => ["pass_through", "$1"],
    803 => ["pass_through", "$1"], 804 => ["empty", "nil"], 805 => ["empty", "nil"],
    807 => ["pass_through", "$1"], 808 => ["empty", "nil"], 809 => ["empty", "nil"],
    812 => ["pass_through", "$1"], 813 => ["empty", "nil"], 814 => ["pass_through", "$1"],
    815 => ["pass_through", "$1"], 816 => ["pass_through", "$1"], 817 => ["pass_through", "$1"],
    818 => ["pass_through", "$1"],
    819 => ["empty", "nil"], 827 => ["pass_through", "$1"], 830 => ["empty", "nil"],
    832 => ["pass_through", "$1"], 833 => ["pass_through", "$1"], 834 => ["pass_through", "$1"],
    836 => ["pass_through", "$1"], 837 => ["pass_through", "$1"],
    838 => ["ported", "@builder.operator(\".\")"], 839 => ["ported", "@builder.operator(\"::\")"],
    840 => ["ported", "@builder.operator(\".\")"], 841 => ["ported", "@builder.operator(\"&.\")"],
    842 => ["pass_through", "$1"], 843 => ["ported", "@builder.operator(\"::\")"],
    398 => ["empty", "nil"],
    10 => ["pass_through", "$2"], 12 => ["pass_through", "$2"],
    24 => ["pass_through", "$3"], 26 => ["pass_through", "$1"],
    28 => ["pass_through", "$2"], 29 => ["pass_through", "$2"],
    30 => ["pass_through", "$2"], 31 => ["pass_through", "$2"],
    32 => ["pass_through", "$2"], 38 => ["pass_through", "$3"],
    40 => ["pass_through", "$1"], 41 => ["pass_through", "$1"],
    44 => ["pass_through", "$1"], 47 => ["pass_through", "$1"],
    49 => ["pass_through", "$1"], 50 => ["pass_through", "$1"],
    51 => ["pass_through", "$1"], 52 => ["pass_through", "$1"],
    53 => ["pass_through", "$1"], 54 => ["pass_through", "$1"],
    55 => ["pass_through", "$2"],
    56 => ["pass_through", "$1"], 58 => ["pass_through", "$1"],
    59 => ["pass_through", "$1"], 62 => ["pass_through", "$1"],
    65 => ["pass_through", "$3"], 67 => ["pass_through", "$1"],
    73 => ["ported", "@builder.unary(:\"!\", $2)"],
    716 => ["pass_through", "$3"], 717 => ["empty", "nil"],
    493 => ["empty", "nil"], 494 => ["empty", "nil"],
    495 => ["ported", "@builder.lambda_node($7, $8)"],
    498 => ["pass_through", "$2"], 499 => ["empty", "nil"], 500 => ["pass_through", "$3"],
    369 => ["pass_through", "$1"], 620 => ["pass_through", "$1"]
  }.freeze
end
